pub const RUNTIME_RS: &str = r#"
// nadash generated program - runtime
// This file was generated by nadash. Do not edit manually.
#![allow(unused_imports, unused_variables, unused_mut, dead_code, non_snake_case)]

use std::cell::RefCell;
use std::cmp::Ordering;
use std::collections::HashMap;
use std::rc::Rc;

#[derive(Clone, Debug)]
enum Value {
    Null,
    Bool(bool),
    Num(f64),
    Str(String),
    Arr(Rc<RefCell<Vec<Value>>>),
    Obj(Rc<RefCell<HashMap<String, Value>>>),
}

fn rt_err(msg: String) -> ! {
    std::panic::panic_any(format!("実行時エラー: {}", msg))
}

impl Value {
    fn is_arr(&self) -> bool {
        matches!(self, Value::Arr(_))
    }
    fn truthy(&self) -> bool {
        !matches!(self, Value::Null | Value::Bool(false))
    }
    fn num(&self) -> f64 {
        match self {
            Value::Num(n) => *n,
            Value::Str(s) => s.trim().parse::<f64>().unwrap_or_else(|_| {
                rt_err(format!("数値が必要ですが「{}」が指定されました", s))
            }),
            Value::Bool(b) => {
                if *b { 1.0 } else { 0.0 }
            }
            other => rt_err(format!(
                "数値が必要ですが「{}」が指定されました",
                rt_tostr(other.clone())
            )),
        }
    }
    fn typename(&self) -> &'static str {
        match self {
            Value::Null => "無効",
            Value::Bool(_) => "真偽値",
            Value::Num(_) => "数値",
            Value::Str(_) => "文字列",
            Value::Arr(_) => "配列",
            Value::Obj(_) => "オブジェクト",
        }
    }
}

fn rt_fmt_num(v: f64) -> String {
    if v.is_nan() {
        return "nan".to_string();
    }
    if v.is_infinite() {
        return if v > 0.0 { "inf".to_string() } else { "-inf".to_string() };
    }
    if v.fract() == 0.0 && v.abs() < 1e15 {
        return format!("{}", v as i64);
    }
    let exp = if v == 0.0 { 0 } else { v.abs().log10().floor() as i32 };
    if exp < -4 || exp >= 14 {
        let s = format!("{:.13e}", v);
        return s;
    }
    let dec = (13 - exp).max(0) as usize;
    let mut s = format!("{:.*}", dec, v);
    if s.contains('.') {
        while s.ends_with('0') {
            s.pop();
        }
        if s.ends_with('.') {
            s.pop();
        }
    }
    s
}

fn rt_tostr(v: Value) -> String {
    match v {
        Value::Null => "無効".to_string(),
        Value::Bool(b) => (if b { "はい" } else { "いいえ" }).to_string(),
        Value::Num(n) => rt_fmt_num(n),
        Value::Str(s) => s,
        Value::Arr(a) => {
            let items = a.borrow();
            let ps: Vec<String> = items.iter().map(|x| rt_tostr(x.clone())).collect();
            format!("[{}]", ps.join(","))
        }
        Value::Obj(o) => {
            let m = o.borrow();
            let mut keys: Vec<&String> = m.keys().collect();
            keys.sort();
            let ps: Vec<String> = keys
                .iter()
                .map(|k| format!("{}:{}", k, rt_tostr(m.get(*k).cloned().unwrap_or(Value::Null))))
                .collect();
            format!("{{{}}}", ps.join(","))
        }
    }
}

fn rt_add(a: Value, b: Value) -> Value {
    if matches!(a, Value::Arr(_) | Value::Obj(_)) || matches!(b, Value::Arr(_) | Value::Obj(_)) {
        rt_err("配列やオブジェクトは足し算できません".to_string())
    }
    let soft_num = |v: &Value| -> Option<f64> {
        match v {
            Value::Num(n) => Some(*n),
            Value::Str(s) => s.trim().parse::<f64>().ok(),
            _ => None,
        }
    };
    if let (Some(na), Some(nb)) = (soft_num(&a), soft_num(&b)) {
        return Value::Num(na + nb);
    }
    Value::Str(format!("{}{}", rt_tostr(a), rt_tostr(b)))
}

fn rt_sub(a: Value, b: Value) -> Value {
    Value::Num(a.num() - b.num())
}
fn rt_mul(a: Value, b: Value) -> Value {
    Value::Num(a.num() * b.num())
}
fn rt_div(a: Value, b: Value) -> Value {
    let d = b.num();
    if d == 0.0 {
        rt_err("ゼロ除算エラー".to_string());
    }
    Value::Num(a.num() / d)
}
fn rt_mod(a: Value, b: Value) -> Value {
    let d = b.num();
    if d == 0.0 {
        rt_err("ゼロ除算エラー".to_string());
    }
    Value::Num(a.num() % d)
}
fn rt_pow(a: Value, b: Value) -> Value {
    Value::Num(a.num().powf(b.num()))
}

fn rt_eq(a: Value, b: Value) -> bool {
    match (&a, &b) {
        (Value::Null, Value::Null) => true,
        (Value::Arr(x), Value::Arr(y)) => Rc::ptr_eq(x, y),
        (Value::Obj(x), Value::Obj(y)) => Rc::ptr_eq(x, y),
        (Value::Bool(x), Value::Bool(y)) => x == y,
        _ => match (
            a.clone().num_checked(),
            b.clone().num_checked(),
        ) {
            (Some(na), Some(nb)) => na == nb,
            _ => rt_tostr(a) == rt_tostr(b),
        },
    }
}

impl Value {
    fn num_checked(&self) -> Option<f64> {
        match self {
            Value::Num(n) => Some(*n),
            Value::Str(s) => s.trim().parse::<f64>().ok(),
            _ => None,
        }
    }
}

fn rt_lt(a: Value, b: Value) -> bool {
    if let (Value::Str(x), Value::Str(y)) = (&a, &b) {
        return x < y;
    }
    a.num() < b.num()
}
fn rt_le(a: Value, b: Value) -> bool {
    rt_eq(a.clone(), b.clone()) || rt_lt(a, b)
}

fn arr(items: Vec<Value>) -> Value {
    Value::Arr(Rc::new(RefCell::new(items)))
}

fn obj(pairs: Vec<(&str, Value)>) -> Value {
    let mut m = HashMap::new();
    for (k, v) in pairs {
        m.insert(k.to_string(), v);
    }
    Value::Obj(Rc::new(RefCell::new(m)))
}

fn rt_idx(base: Value, idx: Value) -> Value {
    match (&base, &idx) {
        (Value::Str(s), _) => {
            let chars: Vec<char> = s.chars().collect();
            let n = idx.num();
            let i = n as i64 - 1;
            if i < 0 || i as usize >= chars.len() {
                Value::Null
            } else {
                Value::Str(chars[i as usize].to_string())
            }
        }
        (Value::Arr(a), _) => {
            let i = idx.num() as i64;
            if i < 0 {
                return Value::Null;
            }
            a.borrow().get(i as usize).cloned().unwrap_or(Value::Null)
        }
        (Value::Obj(o), _) => {
            let key = rt_tostr(idx);
            o.borrow().get(&key).cloned().unwrap_or(Value::Null)
        }
        _ => rt_err("添字アクセスできるのは配列・オブジェクト・文字列だけです".to_string()),
    }
}

fn rt_setidx(base: Value, idx: Value, val: Value) {
    match &base {
        Value::Arr(a) => {
            let i = idx.num() as i64;
            if i < 0 {
                rt_err("添字は0以上にしてください".to_string());
            }
            let mut v = a.borrow_mut();
            let n = i as usize;
            while v.len() <= n {
                v.push(Value::Null);
            }
            v[n] = val;
        }
        Value::Obj(o) => {
            o.borrow_mut().insert(rt_tostr(idx), val);
        }
        _ => rt_err("代入できるのは配列・オブジェクトだけです".to_string()),
    }
}

fn rt_len(v: Value) -> Value {
    match v {
        Value::Str(s) => Value::Num(s.chars().count() as f64),
        Value::Arr(a) => Value::Num(a.borrow().len() as f64),
        Value::Obj(o) => Value::Num(o.borrow().len() as f64),
        other => rt_err(format!(
            "『文字数』には文字列か配列を指定してください（{}）",
            other.typename()
        )),
    }
}

fn rt_print(v: Value) -> Value {
    println!("{}", rt_tostr(v));
    Value::Null
}

fn vcmp(a: &Value, b: &Value) -> Ordering {
    if let (Value::Num(x), Value::Num(y)) = (a, b) {
        return x.partial_cmp(y).unwrap_or(Ordering::Equal);
    }
    if let (Value::Str(x), Value::Str(y)) = (a, b) {
        return x.cmp(y);
    }
    rt_tostr(a.clone()).cmp(&rt_tostr(b.clone()))
}

fn rt_rand_seed() -> u64 {
    use std::sync::atomic::{AtomicU64, Ordering};
    static S: AtomicU64 = AtomicU64::new(0);
    let mut s = S.load(Ordering::Relaxed);
    if s == 0 {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(12345);
        s = nanos ^ ((std::process::id() as u64) << 32) ^ 0x9E3779B97F4A7C15;
        if s == 0 {
            s = 88172645463325252;
        }
        S.store(s, Ordering::Relaxed);
    }
    s ^= s << 13;
    s ^= s >> 7;
    s ^= s << 17;
    S.store(s, Ordering::Relaxed);
    s
}

fn rt_rand(lo: Value, hi: Value) -> Value {
    let mut a = lo.num() as i64;
    let mut b = hi.num() as i64;
    if b < a {
        std::mem::swap(&mut a, &mut b);
    }
    let r = (rt_rand_seed() >> 1) as i64;
    Value::Num((a + r % (b - a + 1)) as f64)
}

fn rt_round(v: Value) -> Value {
    Value::Num((v.num() + 0.5).floor())
}
fn rt_ceil(v: Value) -> Value {
    Value::Num(v.num().ceil())
}
fn rt_floor(v: Value) -> Value {
    Value::Num(v.num().floor())
}
fn rt_abs(v: Value) -> Value {
    Value::Num(v.num().abs())
}
fn rt_sign(v: Value) -> Value {
    let n = v.num();
    Value::Num(if n > 0.0 { 1.0 } else if n < 0.0 { -1.0 } else { 0.0 })
}
fn rt_sqrt(v: Value) -> Value {
    Value::Num(v.num().sqrt())
}
fn rt_sin(v: Value) -> Value {
    Value::Num(v.num().sin())
}
fn rt_cos(v: Value) -> Value {
    Value::Num(v.num().cos())
}
fn rt_tan(v: Value) -> Value {
    Value::Num(v.num().tan())
}

fn rt_mid(s: Value, a: Value, b: Value) -> Value {
    if let Value::Str(st) = s {
        let chars: Vec<char> = st.chars().collect();
        let ai = (a.num() as i64 - 1).max(0) as usize;
        let bi = (b.num() as i64).min(chars.len() as i64) as usize;
        if ai >= bi {
            return Value::Str(String::new());
        }
        Value::Str(chars[ai..bi].iter().collect())
    } else {
        rt_err("『切り取る』には文字列を指定してください".to_string())
    }
}

fn rt_replace(s: Value, from: Value, to: Value) -> Value {
    if let Value::Str(st) = s {
        let f = rt_tostr(from);
        let t = rt_tostr(to);
        Value::Str(st.replace(&f, &t))
    } else {
        rt_err("『置換』には文字列を指定してください".to_string())
    }
}

fn rt_split(s: Value, d: Value) -> Value {
    let st = rt_tostr(s);
    let dd = rt_tostr(d);
    let parts: Vec<Value> = if dd.is_empty() {
        st.chars().map(|c| Value::Str(c.to_string())).collect()
    } else {
        st.split(dd.as_str()).map(|p| Value::Str(p.to_string())).collect()
    };
    arr(parts)
}

fn rt_upper(s: Value) -> Value {
    Value::Str(rt_tostr(s).to_uppercase())
}
fn rt_lower(s: Value) -> Value {
    Value::Str(rt_tostr(s).to_lowercase())
}
fn rt_trim(s: Value) -> Value {
    Value::Str(rt_tostr(s).trim().to_string())
}

fn rt_push(t: Value, v: Value) -> Value {
    match t {
        Value::Arr(a) => {
            a.borrow_mut().push(v);
            Value::Arr(a)
        }
        _ => rt_err("『配列追加』には配列を指定してください".to_string()),
    }
}

fn rt_sort(t: Value) -> Value {
    match t {
        Value::Arr(a) => {
            a.borrow_mut().sort_by(vcmp);
            Value::Arr(a)
        }
        _ => rt_err("『配列ソート』には配列を指定してください".to_string()),
    }
}

fn rt_reverse(t: Value) -> Value {
    match t {
        Value::Arr(a) => {
            let v = a.borrow();
            let items: Vec<Value> = v.iter().rev().cloned().collect();
            drop(v);
            arr(items)
        }
        _ => rt_err("『配列逆順』には配列を指定してください".to_string()),
    }
}

fn rt_join(t: Value, sep: Value) -> Value {
    match t {
        Value::Arr(a) => {
            let items = a.borrow();
            let ps: Vec<String> = items.iter().map(|x| rt_tostr(x.clone())).collect();
            Value::Str(ps.join(&rt_tostr(sep)))
        }
        _ => rt_err("『配列接続』には配列を指定してください".to_string()),
    }
}

fn rt_sleep(sec: Value) -> Value {
    std::thread::sleep(std::time::Duration::from_secs_f64(sec.num().max(0.0)));
    Value::Null
}

fn rt_typename(v: Value) -> Value {
    Value::Str(v.typename().to_string())
}

fn rt_jsonenc_str(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn rt_jsonenc(v: Value) -> Value {
    fn enc(v: Value) -> String {
        match v {
            Value::Null => "null".to_string(),
            Value::Bool(b) => b.to_string(),
            Value::Num(n) => rt_fmt_num(n),
            Value::Str(s) => rt_jsonenc_str(&s),
            Value::Arr(a) => {
                let items = a.borrow();
                let ps: Vec<String> = items.iter().map(|x| enc(x.clone())).collect();
                format!("[{}]", ps.join(","))
            }
            Value::Obj(o) => {
                let m = o.borrow();
                let mut keys: Vec<&String> = m.keys().collect();
                keys.sort();
                let ps: Vec<String> = keys
                    .iter()
                    .map(|k| {
                        format!(
                            "{}:{}",
                            rt_jsonenc_str(k),
                            enc(m.get(*k).cloned().unwrap_or(Value::Null))
                        )
                    })
                    .collect();
                format!("{{{}}}", ps.join(","))
            }
        }
    }
    Value::Str(enc(v))
}

struct JsonParser {
    chars: Vec<char>,
    pos: usize,
}

impl JsonParser {
    fn peek(&self) -> char {
        *self.chars.get(self.pos).unwrap_or(&'\0')
    }
    fn skip_ws(&mut self) {
        while matches!(self.peek(), ' ' | '\t' | '\n' | '\r') {
            self.pos += 1;
        }
    }
    fn expect(&mut self, c: char) {
        if self.peek() != c {
            rt_err(format!("JSON解析エラー: '{}' が必要です", c));
        }
        self.pos += 1;
    }
    fn parse_value(&mut self) -> Value {
        self.skip_ws();
        match self.peek() {
            '{' => {
                self.pos += 1;
                let mut m = HashMap::new();
                self.skip_ws();
                if self.peek() == '}' {
                    self.pos += 1;
                    return obj_from_map(m);
                }
                loop {
                    self.skip_ws();
                    let k = match self.parse_value() {
                        Value::Str(s) => s,
                        _ => rt_err("JSON解析エラー: キーは文字列です".to_string()),
                    };
                    self.skip_ws();
                    self.expect(':');
                    let v = self.parse_value();
                    m.insert(k, v);
                    self.skip_ws();
                    match self.peek() {
                        ',' => {
                            self.pos += 1;
                        }
                        '}' => {
                            self.pos += 1;
                            break;
                        }
                        _ => rt_err("JSON解析エラー".to_string()),
                    }
                }
                obj_from_map(m)
            }
            '[' => {
                self.pos += 1;
                let mut items = Vec::new();
                self.skip_ws();
                if self.peek() == ']' {
                    self.pos += 1;
                    return arr(items);
                }
                loop {
                    items.push(self.parse_value());
                    self.skip_ws();
                    match self.peek() {
                        ',' => {
                            self.pos += 1;
                        }
                        ']' => {
                            self.pos += 1;
                            break;
                        }
                        _ => rt_err("JSON解析エラー".to_string()),
                    }
                }
                arr(items)
            }
            '"' => self.parse_string(),
            't' => {
                self.take_lit("true");
                Value::Bool(true)
            }
            'f' => {
                self.take_lit("false");
                Value::Bool(false)
            }
            'n' => {
                self.take_lit("null");
                Value::Null
            }
            _ => {
                let start = self.pos;
                while "+-0123456789.eE".contains(self.peek()) {
                    self.pos += 1;
                }
                let s: String = self.chars[start..self.pos].iter().collect();
                s.parse::<f64>()
                    .map(Value::Num)
                    .unwrap_or_else(|_| rt_err("JSON解析エラー: 不正な数値です".to_string()))
            }
        }
    }
    fn take_lit(&mut self, lit: &str) {
        for c in lit.chars() {
            if self.peek() != c {
                rt_err("JSON解析エラー: 不正なリテラルです".to_string());
            }
            self.pos += 1;
        }
    }
    fn parse_string(&mut self) -> Value {
        self.expect('"');
        let mut out = String::new();
        loop {
            if self.pos >= self.chars.len() {
                rt_err("JSON解析エラー: 文字列が閉じていません".to_string());
            }
            let c = self.chars[self.pos];
            self.pos += 1;
            match c {
                '"' => break,
                '\\' => {
                    let e = self.chars[self.pos];
                    self.pos += 1;
                    match e {
                        'n' => out.push('\n'),
                        't' => out.push('\t'),
                        'r' => out.push('\r'),
                        'b' => out.push('\u{8}'),
                        'f' => out.push('\u{c}'),
                        'u' => {
                            let hex: String =
                                self.chars[self.pos..self.pos + 4].iter().collect();
                            self.pos += 4;
                            let code = u32::from_str_radix(&hex, 16)
                                .unwrap_or_else(|_| rt_err("JSON解析エラー: 不正な\\u".to_string()));
                            out.push(char::from_u32(code).unwrap_or('\u{fffd}'));
                        }
                        other => out.push(other),
                    }
                }
                c => out.push(c),
            }
        }
        Value::Str(out)
    }
}

fn obj_from_map(m: HashMap<String, Value>) -> Value {
    Value::Obj(Rc::new(RefCell::new(m)))
}

fn rt_jsondec(s: Value) -> Value {
    if matches!(s, Value::Arr(_) | Value::Obj(_)) {
        return s;
    }
    let text = rt_tostr(s);
    let mut p = JsonParser {
        chars: text.chars().collect(),
        pos: 0,
    };
    let v = p.parse_value();
    p.skip_ws();
    if p.pos != p.chars.len() {
        rt_err("JSON解析エラー: 余分なデータがあります".to_string());
    }
    v
}

thread_local! {
    static G: RefCell<HashMap<String, Value>> = RefCell::new(HashMap::new());
}

fn gset(k: &str, v: Value) {
    G.with(|g| {
        g.borrow_mut().insert(k.to_string(), v);
    });
}

fn gget(k: &str) -> Value {
    G.with(|g| g.borrow().get(k).cloned()).unwrap_or(Value::Null)
}

fn sore_set(v: Value) {
    gset("それ", v);
}

fn sore_get() -> Value {
    gget("それ")
}

fn main() {
    std::panic::set_hook(Box::new(|info| {
        let msg = info
            .payload()
            .downcast_ref::<String>()
            .cloned()
            .or_else(|| info.payload().downcast_ref::<&str>().map(|s| s.to_string()))
            .unwrap_or_else(|| "不明な実行時エラー".to_string());
        eprintln!("{}", msg);
    }));
    run();
}

fn rt_truthy(v: Value) -> bool {
    v.truthy()
}

fn rt_int(v: Value) -> i64 {
    v.num() as i64
}

fn rt_snapshot(v: Value) -> Vec<Value> {
    match v {
        Value::Arr(a) => a.borrow().clone(),
        _ => rt_err("『反復』には配列を指定してください".to_string()),
    }
}
"#;

